import abc
from websim_based_stream_generator import WebsimStreamGenerator
from tree_stream_generator import TreeStreamGenerator
from monotonous_stream_generator import MonotonousStreamGenerator
from noise_stream_generator import NoiseStreamGenerator

